[package]
name = "orchestrator"
version = "0.1.0"
authors = ["AnastasiosSoukoulis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nng = "1.0.0-rc.2"


[profile.release]
opt-level = 3
lto = true